# Cholesky Decomposition

In [7]:
import numpy as np
import scipy
import scipy.linalg

Create Random Matrix

In [8]:
n=5

In [9]:
P=np.random.randn(n,n)
print(P)

[[-0.69635328  1.91825182  0.91761557  0.71027839 -0.82873888]
 [ 0.17356002 -1.19226887 -1.10772575 -1.02176333  0.34509317]
 [-0.27929045  0.16215149  0.75204951  0.238814   -1.89753586]
 [-0.88210167  0.68636467 -0.24760135 -0.78347778 -0.99119227]
 [ 0.16263402  0.33678494  0.71221614 -0.03814523 -0.21770675]]


Make a covariance matrix

In [10]:
P=P @ P.T
print(P)

[[ 6.19791982 -4.43612596  2.93781072  1.96862404  1.33965653]
 [-4.43612596  3.84177406 -1.97370449 -0.23867923 -1.1984053 ]
 [ 2.93781072 -1.97370449  4.32754918  1.86516655  0.9488066 ]
 [ 1.96862404 -0.23867923  1.86516655  2.9068058   0.15702706]
 [ 1.33965653 -1.1984053   0.9488066   0.15702706  0.69597703]]


Cholesky Decomposition with scipy, note the transpose operator - scipy returns upper-triangular matrix

In [11]:
L=scipy.linalg.cholesky(P).T
print(L)

[[ 2.48956217  0.          0.          0.          0.        ]
 [-1.78189001  0.81648151  0.          0.          0.        ]
 [ 1.18005115  0.15801567  1.70588965  0.          0.        ]
 [ 0.7907511   1.43340938  0.41358986  0.23621911  0.        ]
 [ 0.53810929 -0.29339763  0.21113413  0.27412056  0.44789905]]


Check Result

In [12]:
print(P-L @ L.T)

[[  8.88178420e-16   0.00000000e+00   0.00000000e+00  -2.22044605e-16
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -2.77555756e-16
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [ -2.22044605e-16  -2.77555756e-16   0.00000000e+00   0.00000000e+00
   -2.77555756e-17]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -2.77555756e-17
    0.00000000e+00]]


Cholesky Decomposition with numpy, returning lower-triangular matrix

In [14]:
nL = np.linalg.cholesky(P)
print (nL)

[[ 2.48956217  0.          0.          0.          0.        ]
 [-1.78189001  0.81648151  0.          0.          0.        ]
 [ 1.18005115  0.15801567  1.70588965  0.          0.        ]
 [ 0.7907511   1.43340938  0.41358986  0.23621911  0.        ]
 [ 0.53810929 -0.29339763  0.21113413  0.27412056  0.44789905]]


In [15]:
print(L-nL)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
