# Cholesky Decomposition

In [2]:
import numpy as np
import scipy
import scipy.linalg
from pprint import pprint

Create Random Matrix

In [6]:
n=5

In [7]:
P=np.random.randn(n,n)
pprint(P)

array([[-0.12461335, -1.24977108,  0.3464285 , -1.44551703,  0.19209124],
       [-0.70647476, -0.92909219,  1.85517894, -0.46308859,  0.71106954],
       [ 0.9276042 , -0.55915506, -0.50147125,  0.09121574,  1.32326057],
       [ 0.8166988 , -0.880774  , -1.61513538, -0.17533824, -0.04826378],
       [ 1.01129142, -0.79890223,  1.12770598, -0.41618392,  0.91637582]])


In [8]:
P=P @ P.T
pprint(P)

array([[ 3.82388747,  2.69786826,  0.53183289,  0.68364874,  2.04072271],
       [ 2.69786826,  5.52407872, -0.16745195, -2.70814375,  2.96423531],
       [ 0.53183289, -0.16745195,  3.18391622,  1.98014728,  1.99391774],
       [ 0.68364874, -2.70814375,  1.98014728,  4.08449495, -0.26307983],
       [ 2.04072271,  2.96423531,  1.99391774, -0.26307983,  3.94562961]])


In [14]:
L=scipy.linalg.cholesky(P).T
pprint(L)

array([[ 1.95547628,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.37964765,  1.90280085,  0.        ,  0.        ,  0.        ],
       [ 0.27197103, -0.2851986 ,  1.74029013,  0.        ,  0.        ],
       [ 0.34960728, -1.67672755,  0.80840766,  0.70521731,  0.        ],
       [ 1.04359369,  0.80115779,  1.11394045, -0.26250409,  0.95127088]])


Check Result

In [16]:
pprint(P-L @ L.T)

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,  -5.55111512e-17,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,  -5.55111512e-17,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,  -5.55111512e-17],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -5.55111512e-17,   0.00000000e+00]])
